version: 0.2

phases:
  pre_build:
    commands:
      - ./scripts/echo-brand.sh
      - export PIPELINE_ID=$FOX_PIPELINE_ID
      - . ./scripts/assume-role.sh
      - . ./scripts/export-xilution-config.sh
      - . ./scripts/export-terraform-vars.sh stage
  build:
    commands:
      - ./scripts/terraform.sh stage down $ADD_INFRA_TERRAFORM_PATH_STAGE additional-infrastructure.tfstate $TERRAFORM_PROVIDER integration fox
      - ./scripts/terraform.sh stage down $TERRAFORM_PATH terraform.tfstate $TERRAFORM_PROVIDER integration fox
