version: 0.2

phases:
  pre_build:
    commands:
      - . ./scripts/assume-role.sh
  build:
    commands:
      - ./scripts/terraform-stage.sh up
      - ./scripts/additional-infrastructure-stage.sh up
