version: 0.2

phases:
  pre_build:
    commands:
      - . ./scripts/assume-role.sh
  build:
    commands:
      - ./scripts/cloudformation-create-or-update-stack-stage.sh
      - ./scripts/additional-infrastructure-up-stage.sh
