version: 0.2

phases:
  pre_build:
    commands:
      - |
        . ./scripts/assume-role.sh \
          $CLIENT_AWS_ACCOUNT \
          xilution-developer-role \
      - |
        . ./scripts/terraform-init-stage.sh \
          $CLIENT_AWS_ACCOUNT \
          $FOX_PIPELINE_ID \
          $STAGE_NAME
  build:
    commands:
      - |
        terraform destroy \
          -var="organization_id=$XILUTION_ORGANIZATION_ID" \
          -var="fox_pipeline_id=$FOX_PIPELINE_ID" \
          -var="stage_name=$STAGE_NAME" \
          -var="client_aws_account=$CLIENT_AWS_ACCOUNT" \
          -var="client_aws_region=$CLIENT_AWS_REGION" \
          -var="xilution_aws_account=$XILUTION_AWS_ACCOUNT" \
          -var="xilution_aws_region=$XILUTION_AWS_REGION" \
          -var="xilution_environment=$XILUTION_ENVIRONMENT" \
          -var="xilution_pipeline_type=$PIPELINE_TYPE" \
          -auto-approve \
          ./terraform/stage
