version: 0.2

phases:
  pre_build:
    commands:
      - . ./scripts/assume-role.sh
  build:
    commands:
      - ./scripts/delete-fox-source-bucket-contents.sh
      - ./scripts/additional-infrastructure-trunk.sh down
      - ./scripts/terraform-trunk.sh down
