version: 0.2

phases:
  pre_build:
    commands:
      - . ./scripts/assume-role.sh
  build:
    commands:
      - ./scripts/terraform-plan-trunk.sh
      - ./scripts/terraform-apply-trunk.sh
      - ./scripts/cloudformation-create-or-update-stack-trunk.sh
      - ./scripts/additional-infrastructure-up-trunk.sh
