version: 0.2

phases:
  pre_build:
    commands:
      - . ./scripts/assume-role.sh
  build:
    commands:
      - ./scripts/terraform-trunk.sh up
      - ./scripts/additional-infrastructure-trunk.sh up
