version: 0.2

env:
  exported-variables:
    - API_BASE_URL

phases:
  pre_build:
    commands:
      - . ./scripts/assume-role.sh
  build:
    commands:
      - ./scripts/deploy-up.sh
      - . ./scripts/export-api-base-url.sh
