AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  PipelineId:
    Type: String

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "xilution-fox-${PipelineId}-source-code"
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "xilution-fox-${PipelineId}-lambda-role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "xilution-fox-${PipelineId}-api"
      ProtocolType: HTTP
      Tags:
        originator: "xilution.com"

Outputs:
  SourceBucket:
    Value: !Ref SourceBucket
    Export:
      Name: !Sub "${AWS::StackName}-source-bucket"
  LambdaRole:
    Value:
      Fn::GetAtt:
        - LambdaRole
        - Arn
    Export:
      Name: !Sub "${AWS::StackName}-lambda-role-arn"
  Api:
    Value: !Ref Api
    Export:
      Name: !Sub "${AWS::StackName}-api"
  ApiBaseUrl:
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-api-base-url"
