AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  PipelineId:
    Type: String
  StageName:
    Type: String
  EndpointId:
    Type: String
  SourceVersion:
    Type: String
  Method:
    Type: String
  Path:
    Type: String
  TrunkStackName:
    Type: String
  StageStackName:
    Type: String

Resources:
  Route:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Fn::ImportValue: !Sub "${TrunkStackName}-api"
      RouteKey: !Sub "${Method} ${Path}"
      Target: !Join
        - /
        - - integrations
          - Fn::ImportValue: !Sub "${StageStackName}-integration"
