AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Method:
    Type: String
  Path:
    Type: String
  ApiLambdaStackName:
    Type: String

Resources:
  Route:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Fn::ImportValue: !Sub "${ApiLambdaStackName}-api"
      RouteKey: !Sub "${Method} ${Path}"
      Target: !Join
        - /
        - - integrations
          - Fn::ImportValue: !Sub "${ApiLambdaStackName}-integration"
